# Generated by Django 2.2.6 on 2019-10-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interlink', '0003_redirectproductoldtonewdictionary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedirectProductOldToNewDictionary',
        ),
    ]
