# Generated by Django 2.2.1 on 2019-09-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_form',
            new_name='EmailForm',
        ),
    ]
