# Generated by Django 2.2.1 on 2019-09-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_form', '0002_auto_20190926_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailForm',
            new_name='EmailModel',
        ),
    ]
