# Generated by Django 2.2.1 on 2019-09-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_form', '0003_auto_20190926_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
