# Generated by Django 2.2.1 on 2019-09-30 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_form', '0004_auto_20190927_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='timestamp',
            field=models.DateField(default=datetime.date(2019, 9, 30)),
        ),
    ]
