# Generated by Django 2.2.1 on 2019-09-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_form', '0005_emailmodel_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmodel',
            options={'verbose_name': 'обратный звонок', 'verbose_name_plural': 'обратные звонки'},
        ),
    ]
