# Generated by Django 2.2.1 on 2019-10-01 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_form', '0006_auto_20190930_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
