# Generated by Django 2.2.1 on 2019-09-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190918_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
