# Generated by Django 2.2.1 on 2019-10-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogs_number_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
