# Generated by Django 2.2.1 on 2019-10-04 15:10

import blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_orders_order_n'),
        ('blogs', '0005_auto_20191001_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='page_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='page_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='OldBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=blogs.models.upload_image_path)),
                ('publish', models.DateField(auto_now=True)),
                ('number_views', models.IntegerField(default=0)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('page_description', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
            ],
            options={
                'verbose_name': 'Старая Статья',
                'verbose_name_plural': 'Старые Статьи',
            },
        ),
    ]
