# Generated by Django 2.2.1 on 2019-10-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20191004_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'default_related_name': 'blogs', 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='oldblogs',
            options={'default_related_name': 'oldblogs', 'verbose_name': 'oldblogs', 'verbose_name_plural': 'Старые Статьи'},
        ),
        migrations.AlterField(
            model_name='oldblogs',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='old_categories', to='products.Categories'),
        ),
    ]
