# Generated by Django 2.2.1 on 2019-10-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20191004_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'default_related_name': 'blogs', 'verbose_name': 'blogs', 'verbose_name_plural': 'Статьи'},
        ),
    ]
