# Generated by Django 2.2.1 on 2019-10-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20191004_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldblogs',
            name='number_views',
            field=models.IntegerField(default=1),
        ),
    ]
