# Generated by Django 2.2.6 on 2019-10-17 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20191004_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
