# Generated by Django 2.2.6 on 2019-10-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20191018_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.CharField(default='Admin', max_length=255),
        ),
        migrations.AddField(
            model_name='blogs',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
