# Generated by Django 2.2.6 on 2019-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20191024_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldblogs',
            name='author',
            field=models.CharField(default='Admin', max_length=255),
        ),
        migrations.AddField(
            model_name='oldblogs',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
