# Generated by Django 2.2.1 on 2019-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191002_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Россия', max_length=255, null=True),
        ),
    ]
