# Generated by Django 2.2.1 on 2019-09-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photostatistic',
            name='unchecked_count',
            field=models.IntegerField(default=0),
        ),
    ]
