# Generated by Django 2.2.1 on 2019-09-28 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_photos', '0002_photostatistic_unchecked_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photostatistic',
            name='checked_date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
