# Generated by Django 2.2.6 on 2019-10-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='minus',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='groups',
            name='plus',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
