# Generated by Django 2.2.6 on 2019-10-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0002_auto_20191025_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernel',
            name='chk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='chk',
            field=models.BooleanField(default=False),
        ),
    ]
