# Generated by Django 2.2.6 on 2019-10-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0003_auto_20191027_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanKernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InfoKernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
