# Generated by Django 2.2.6 on 2019-10-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0004_cleankernel_infokernel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleankernel',
            name='minus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='infokernel',
            name='minus',
            field=models.TextField(blank=True),
        ),
    ]
