# Generated by Django 2.2.6 on 2019-10-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0005_auto_20191029_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='KernelTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=500)),
                ('freq', models.PositiveIntegerField()),
                ('chk', models.BooleanField(default=False)),
            ],
        ),
    ]
