# Generated by Django 2.2.6 on 2019-10-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0007_auto_20191029_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerneltmp',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
