# Generated by Django 2.2.6 on 2019-10-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0009_kernelcleanedfromtrash_kernelreadycommercial_kernelreadyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernelreadycommercial',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kernelreadyinfo',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
