# Generated by Django 2.2.6 on 2019-11-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0010_auto_20191031_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerneltmp',
            name='group_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
