# Generated by Django 2.2.6 on 2019-11-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0012_auto_20191105_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='parent',
            field=models.IntegerField(),
        ),
    ]
