# Generated by Django 2.2.6 on 2019-11-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0013_auto_20191106_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
