# Generated by Django 2.2.6 on 2019-11-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0014_auto_20191106_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='old_group_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
