# Generated by Django 2.2.6 on 2019-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_dict', '0016_auto_20191128_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='value_price',
            field=models.BooleanField(default=True),
        ),
    ]
