# Generated by Django 2.2.6 on 2019-11-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_dict', '0014_auto_20191106_1250'),
       ]

    operations = [
        migrations.CreateModel(
            name='AdGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('labels', models.CharField(blank=True, max_length=255)),
                ('max_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('max_cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('final_url', models.CharField(blank=True, max_length=500)),
                ('critarion_type', models.CharField(blank=True, max_length=100)),
                ('description1', models.CharField(blank=True, max_length=90)),
                ('description2', models.CharField(blank=True, max_length=90)),
                ('description3', models.CharField(blank=True, max_length=90)),
                ('headline1', models.CharField(blank=True, max_length=30)),
                ('headline2', models.CharField(blank=True, max_length=30)),
                ('headline3', models.CharField(blank=True, max_length=30)),
                ('path1', models.CharField(blank=True, max_length=15)),
                ('path2', models.CharField(blank=True, max_length=15)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group_dict.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Negative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative', models.CharField(max_length=255, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_ads_work.AdGroups')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_ads_work.AdGroups')),
            ],
        ),
    ]
