# Generated by Django 2.2.6 on 2019-11-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adgroups',
            old_name='group_name',
            new_name='ad_group_name',
        ),
    ]
