# Generated by Django 2.2.6 on 2019-11-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0002_auto_20191126_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroups',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='adgroups',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='adgroups',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='adgroups',
            name='headline1',
        ),
        migrations.RemoveField(
            model_name='adgroups',
            name='headline2',
        ),
        migrations.RemoveField(
            model_name='adgroups',
            name='headline3',
        ),
        migrations.RemoveField(
            model_name='adgroups',
            name='path1',
        ),
        migrations.RemoveField(
            model_name='adgroups',
            name='path2',
        ),
        migrations.AlterField(
            model_name='adgroups',
            name='max_cpc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='adgroups',
            name='max_cpm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline1', models.CharField(blank=True, max_length=30)),
                ('headline2', models.CharField(blank=True, max_length=30)),
                ('headline3', models.CharField(blank=True, max_length=30)),
                ('description1', models.CharField(blank=True, max_length=90)),
                ('description2', models.CharField(blank=True, max_length=90)),
                ('description3', models.CharField(blank=True, max_length=90)),
                ('path1', models.CharField(blank=True, max_length=15)),
                ('path2', models.CharField(blank=True, max_length=15)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ads_work.AdGroups')),
            ],
        ),
    ]
