# Generated by Django 2.2.6 on 2019-11-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0004_auto_20191127_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroups',
            name='critarion_type',
        ),
    ]
