# Generated by Django 2.2.6 on 2019-11-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0005_remove_adgroups_critarion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline1', models.CharField(blank=True, max_length=30)),
                ('headline2', models.CharField(blank=True, max_length=30)),
                ('headline3', models.CharField(blank=True, max_length=30)),
                ('description1', models.CharField(blank=True, max_length=90)),
                ('description2', models.CharField(blank=True, max_length=90)),
                ('description3', models.CharField(blank=True, max_length=90)),
                ('path1', models.CharField(blank=True, max_length=15)),
                ('path2', models.CharField(blank=True, max_length=15)),
                ('variant', models.CharField(choices=[('one', 1), ('second', 2), ('third', 3)], default='one', max_length=20)),
                ('camaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ads_work.Campaigns')),
            ],
        ),
    ]
