# Generated by Django 2.2.6 on 2019-11-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0006_addstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='variant',
            field=models.CharField(choices=[('one', 1), ('second', 2), ('third', 3)], default='one', max_length=20),
        ),
    ]
