# Generated by Django 2.2.6 on 2019-11-28 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0007_adds_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='camp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_ads_work.Campaigns'),
        ),
    ]
