# Generated by Django 2.2.6 on 2019-11-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0008_adds_camp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroups',
            name='inner_labels',
            field=models.CharField(default='generic', max_length=20),
        ),
    ]
