# Generated by Django 2.2.6 on 2019-11-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0009_adgroups_inner_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroups',
            name='labels',
        ),
    ]
