# Generated by Django 2.2.6 on 2019-11-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0010_remove_adgroups_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='labels',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
