# Generated by Django 2.2.6 on 2019-12-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0013_auto_20191203_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroups',
            name='chk',
            field=models.BooleanField(default=False),
        ),
    ]
