# Generated by Django 2.2.6 on 2019-12-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0014_adgroups_chk'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='fast_link_yand',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='fast_link_yand_desc',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='fast_link_yand_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
