# Generated by Django 2.2.6 on 2019-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0015_auto_20191205_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='criterion_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
