# Generated by Django 2.2.6 on 2019-12-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ads_work', '0016_keywords_criterion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroups',
            name='dont_use',
            field=models.BooleanField(default=False),
        ),
    ]
