# Generated by Django 2.2.1 on 2019-09-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=500, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_n', models.CharField(max_length=50)),
                ('oem_n', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('cat_n', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('car', models.CharField(max_length=255, null=True)),
                ('car_model', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('cond', models.BooleanField(default=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('real_weight', models.FloatField(blank=True, null=True)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
                ('cat', models.ManyToManyField(blank=True, related_name='cat', to='products.Categories')),
                ('cross', models.ManyToManyField(to='products.Cross', verbose_name='cross verbose name')),
            ],
        ),
    ]
