# Generated by Django 2.2.1 on 2019-09-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='car_model',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
