# Generated by Django 2.2.1 on 2019-09-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190910_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cat',
        ),
        migrations.AddField(
            model_name='products',
            name='cat',
            field=models.ManyToManyField(to='products.Categories'),
        ),
    ]
