# Generated by Django 2.2.1 on 2019-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190911_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='car',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='cat_n',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='cross',
            field=models.ManyToManyField(null=True, to='products.Cross', verbose_name='cross verbose name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='real_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
