# Generated by Django 2.2.1 on 2019-09-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190911_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cross',
            field=models.ManyToManyField(to='products.Cross', verbose_name='cross verbose name'),
        ),
    ]
