# Generated by Django 2.2.1 on 2019-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191003_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
