# Generated by Django 2.2.1 on 2019-09-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190911_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='condition',
            new_name='cond',
        ),
    ]
