# Generated by Django 2.2.1 on 2019-10-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orders_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_n',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
